# Generated by Django 3.1.5 on 2021-01-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('car_size', models.FloatField(blank=True, null=True)),
                ('leather_seats', models.BooleanField(default=False)),
                ('license_plate', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, unique=True)),
                ('organzation_type', models.IntegerField(choices=[(1, 'Flat'), (2, 'Functional'), (3, 'Divisional'), (4, 'Matrix')])),
                ('tax_id', models.CharField(max_length=10, unique=True)),
                ('creation_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'CarWash',
                'verbose_name_plural': 'CarWashes',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('personal_id', models.CharField(max_length=11, unique=True)),
                ('job_position', models.IntegerField(choices=[(1, 'Manager'), (2, 'Washer'), (3, 'Cleaner')])),
                ('salary', models.PositiveIntegerField()),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.carwash')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street_adress', models.CharField(max_length=100, unique=True)),
                ('zip_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(1, 'Visa'), (2, 'Paypal'), (3, 'Hard Cash')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('waiting_list_id', models.PositiveIntegerField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.car')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.employee')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['waiting_list_id'],
            },
        ),
        migrations.AddField(
            model_name='carwash',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='management.location'),
        ),
    ]
