# Generated by Django 3.1.5 on 2021-01-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, unique=True)),
                ('organzation_type', models.IntegerField(choices=[(1, 'Flat'), (2, 'Functional'), (3, 'Divisional'), (4, 'Matrix')])),
                ('tax_id', models.CharField(max_length=10, unique=True)),
                ('creation_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Car wash',
                'verbose_name_plural': 'Car washes',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street_adress', models.CharField(max_length=100, unique=True)),
                ('zip_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('personal_id', models.CharField(max_length=11, unique=True)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.carwash')),
            ],
            options={
                'verbose_name': 'Washer',
                'verbose_name_plural': 'Washers',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('payment_type', models.IntegerField(choices=[(1, 'Visa'), (2, 'Paypal'), (3, 'Hard Cash')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.car')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.washer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='carwash',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='management.location'),
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Sedan'), (2, 'Coupe'), (3, 'Sports Car'), (4, 'Station Wagon'), (5, 'Hatchback'), (6, 'SUV'), (7, 'Minivan'), (8, 'Pickup Truck')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.carwash')),
            ],
            options={
                'verbose_name': 'Car type',
                'verbose_name_plural': 'Car types',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.cartype'),
        ),
    ]
